### ISSUE TITLE
{Feature request} Ability to edit Orthanc config file

### ISSUE THREAD

**Issue by ranasrule** [gacou54/pyorthanc#18]
It would be awesome if the ability to edit Orthanc config file could be edited specially the ability to  do things like add/edit/delete things like modalities and users etc.

**Comment by gacou54** [comment]
Hi! Sorry for the long delay. I'm not sure if this is possible to edit the config file itself (PyOrthanc only supports Orthanc features accessible through its REST API). I'm still going to check because it would be an interesting feature.

**Comment by gacou54** [comment]
PyOrthanc implements all the features of Orthanc's REST API. Although it does not seem possible to edit the configuration file as such, it is possible to edit Modalities (https://api.orthanc-server.com/#tag/Networking). In the PyOrthanc language, it should look like this:
```python
from pyorthanc import Orthanc

orthanc = Orthanc('http://localhost:8042', username='orthanc', password='orthanc')

assert orthanc.get_modalities() == []

orthanc.put_modalities_id('MyNewModality', {
    'AET': 'MYAET',
    'Host': 'an-ip',
    'Port': 4042,
})
assert orthanc.get_modalities() == ['MyNewModality']

orthanc.delete_modalities_id('MyNewModality')
assert orthanc.get_modalities() == []

```

As for users, Orthanc user management is pretty basic. After looking at the API documentation (https://api.orthanc-server.com/), it seems impossible to edit them from the API. So only possible via the configuration file. For more advanced user management, you might want to look at https://kheops.online/
