### ISSUE TITLE
import pydicom throwing "TypeError"

### ISSUE THREAD

**Issue by uditgoswami** [gacou54/pyorthanc#40]
I am trying to work with pyorthanc, but its throwing me a "TypeError" while doing the import.

Python version: 3.8.12
I am using Miniconda3 as my conda distro ([GCC 7.5.0] :: Anaconda, Inc. on linux)

Please let me know if there is something I am doing wrong here.
![Screenshot from 2023-09-14 17-40-58](https://github.com/gacou54/pyorthanc/assets/30289549/274f8171-cfa2-47fc-85c9-55fd5fb0c909)

**Comment by gacou54** [comment]
Hi, thank you for making an issue! Indeed this is due to the `list` type-hint (should be `typing.List` for python3.8). There is already a fix here #39. I will release a new version with the fix in the next hour.

**Comment by gacou54** [comment]
Fixed in the new release PyOrthanc 1.12.2. 

Simply upgrade pyorthanc (I think it will be `conda update pyorthanc` with conda)
