### ISSUE TITLE
shared-tags in series

### ISSUE THREAD

**Issue by ylemarechal** [gacou54/pyorthanc#53]
It could be interesting to have a property in series for shared tags

For instance : 
series = pyorthanc.Series (client=client, resource=resource)
series.shared-tags

that would be equivalent to the call : 
/series/{resource}/shared-tags

**Comment by gacou54** [comment]
I agree, I will add this in a future release.

**Comment by gacou54** [comment]
Added in PyOrthanc 1.15.0
